name: Update README

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update README
        run: |  
          echo 'Updating README...'  
          # Add your commands here

# Disable the workflow

disabled: true