name: Update README

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Commit Changes
        uses: mssp/git-auto-commit-action@v4
        with:
          commit_message: "Updated README with latest info"
